apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxnetology
  name: nginxnetology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxnetology
  template:
    metadata:
      labels:
        app: nginxnetology
    spec:
      containers:
      - name: myapp
        image: clllagob/nginxnetology:${VERSION} # 
        ports:
        - containerPort: 80

