#services.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxnetology
  name: nginxnetology-service
spec:
  selector:
    app: nginxnetology
  type: NodePort
  ports:
  - name: httpc
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30081