replicaCount: 1

image:
  repository: clllagob/nginxnetology
  pullPolicy: IfNotPresent
  tag: ""

deployment:
  name: nginxnetology

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

service:
  name: nginxnetology-service
  type: NodePort
  port: 80
  nodePort: 30081
  
ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
