name: Build and Deploy Docker

on:
  push:
    branches:
      - main
    paths:
        - 'Docker/**' # Ограничиваем запуск workflow только изменениями в папке Docker

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' # Проверка, что коммит с тегом соответствует формату 'v*' или 'main'
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      YC_CONFIG_DATA: ${{ secrets.YC_CONFIG_DATA }}

    steps:
      - name: Debug
        run: |
          echo "GitHub Ref: ${{ github.ref }}"

      - name: Set version
        id: set_version
        run: |
          if [[ $GITHUB_REF == */v* ]]; then
            echo "::set-output name=VERSION::${GITHUB_REF##*/}"
          else
            echo "::set-output name=VERSION::latest"
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run: |
          echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
          pwd
          cd ./Docker
          docker build -t clllagob/nginxnetology:${{ steps.set_version.outputs.VERSION }} .
          docker push clllagob/nginxnetology:${{ steps.set_version.outputs.VERSION }}

      - name: Install Yandex.Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          exec -l $SHELL
          yc -v

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_DATA" > ~/.kube/config

      - name: Configure yc
        run: |
          mkdir -p ~/.config/yandex-cloud/
          echo "$YC_CONFIG_DATA" > ~/.config/yandex-cloud/config.yaml

      - name: Deploy to Kubernetes
        run: |
          cd ./app/
          kubectl delete -f myapp.yaml
          export VERSION=latest
          envsubst < myapp.yaml | kubectl apply -f -
