name: Build and Deploy Docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: Install qbec
        run: |
          curl -L https://github.com/splunk/qbec/releases/download/v0.15.2/qbec-darwin-amd64.tar.gz -o qbec.tar.gz
          ls -la
          pwd
          tar -xzf qbec.tar.gz qbec 
          rm qbec.tar.gz 
      - name: check qbec
        run: |
          ./qbec version
      - name: Deploy to Kubernetes
        run: |
          kubectl cluster-info
          qbec apply ./qbec/web/components/website.jsonnet
