name: Build and Deploy Docker

on:
  push:
    branches:
      - main
    paths:
      - 'Docker/**' # Ограничиваем запуск workflow только изменениями в папке Docker
  release:
    types: [created] # Событие создания нового тега

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref }} # Получаем значение тега
        run: |
          echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
          pwd
          cd ./Docker
          docker build -t clllagob/nginxnetology:${GITHUB_REF##*/} . # Используем тег при сборке образа
          docker push clllagob/nginxnetology:${GITHUB_REF##*/} # Пушим образ с тегом
      - name: Install Yandex.Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          exec -l $SHELL
          yc -v
      - name: Configure kubectl
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_DATA" > ~/.kube/config
      - name: Configure yc
        env:
          YC_CONFIG_DATA: ${{ secrets.YC_CONFIG_DATA }}
        run: |
          mkdir -p ~/.config/yandex-cloud/
          echo "$YC_CONFIG_DATA" > ~/.config/yandex-cloud/config.yaml
      - name: Install qbec
        run: |
          mkdir bin
          cd bin
          curl -L https://github.com/splunk/qbec/releases/download/v0.15.2/qbec-linux-amd64.tar.gz -o qbec.tar.gz
          tar -xzf qbec.tar.gz qbec
          chmod +x ./qbec 
          sudo mv ./qbec /usr/bin/qbec
          qbec version
      - name: Deploy to Kubernetes
        run: |
          cd ./qbec/website/components/
          qbec apply default --ext-str imageTag="${GITHUB_REF##*/}" --yes # Используем тег для деплоя в Kubernetes
